### ISSUE TITLE
File copying interface, wildcards and name reference

### ISSUE THREAD

**Issue by phutchins** [Storj/libstorj#354]
Copying files from the command line should be easy to use and should follow the conventions set by similar tools and the unix command line. This is a meta feature request which should track the additional features required to enable this functionality.

## Examples

Copying files from local to a bucket
```
$ ls
my_mongo_backup_1.tgz
my_mongo_backup_2.tgz
my_mongo_backup_3.tgz
$ storj add-bucket mongo_backups
$ storj cp ./my_mongo_backup_1.tgz sj://mongo_backups/
or
$ storj cp ./my_mongo_backup_1.tgz sj://mongo_backups/backup_1.tgz
or
$ storj cp ./*.tgz sj://mongo_backups/
```

Downloading files from a bucket to local
```
$ storj cp sj://mongo_backups/my_mongo_backup_1.tgz .
or
$ storj cp sj://mongo_backups/* .
```

Listing files (extra credit)
```
$ storj ls sj://mongo_backups
```

Initially, cp should ignore directories and copy files only. In the future, or sooner if the implementation is not hard, we should allow adding a -r to cp which would recursively copy files preserving the directory structure by using file naming to allow for things like `storj cp sj://mongo_backups/old_backups/backup-1.tgz ./backup-1.tgz`

## Tasks
- [ ] Enable bucket reference by 
- [ ] Enable file reference by name
- [ ] Add `cp` command that allows for the sj://bucket_name[/file_name] syntax in either source or destination file

**Comment by braydonf** [comment]
Closed in https://github.com/Storj/libstorj/pull/416
